export const copy = {
  workbench: {
    topicLabel: "视频主题",
    topicPlaceholder: "输入一句话主题，如：三分钟看懂咖啡的起源",
    scriptLabel: "AI 文案（可编辑）",
    regenerate: "重写文案",
    avatarLabel: "数字人形象",
    upload: "上传形象图（JPG / PNG / WebP，≤10MB）",
    voiceLabel: "音色",
    more: "更多设置",
    speed: "语速",
    aspectLocked: "9:16 竖屏（锁定）",
    subtitleLocked: "字幕已开启（锁定）",
    generate: "生成视频",
    scriptTooLong: (s: number) => `预计 ${s}s，将截断到 60s，建议精简文案`,
    // 生成模式切换（数字人口播 / 电商带货）
    modeGroupLabel: "生成模式",
    modeAvatar: "数字人口播",
    modeEcom: "电商带货",
    aspectBadge: "竖屏 9:16",
    avatarPreviewAlt: "形象预览",
    // 电商带货（图生视频 i2v）表单
    ecomTitle: "电商带货视频",
    ecomSubtitle: "上传产品图、输入卖点，AI 一键生成带货短片",
    ecomTopicLabel: "产品卖点 / 主题",
    ecomTopicPlaceholder: "输入产品卖点，如：316 不锈钢保温杯，24 小时持续锁温",
    ecomTopicRequired: "请先输入产品卖点",
    ecomImageRequired: "请上传产品图后再生成",
    productImageLabel: "产品图（必填）",
    productImageUpload: "上传产品图（JPG / PNG / WebP，≤10MB）",
    productImagePreviewAlt: "产品图预览",
    // 电商带货：视频时长选择器
    durationLabel: "视频时长",
    durationLabelAligned: "视频时长（与文案、字幕一致）",
    durationSeconds: (s: number) => `${s} 秒`,
    durationCustom: "自定义",
    durationCustomLabel: "自定义时长（秒）",
    durationCustomPlaceholder: "5–120",
    durationRange: "请输入 5–120 秒",
    durationHint: "时长越长，生成越慢、消耗额度越多",
    // 文案/画面解耦（电商带货）
    ecomScriptLabel: "AI 口播文案（仅配音）",
    scenePromptLabel: "画面提示词",
    scenePromptGenerate: "AI 生成画面",
    scenePromptPlaceholder: "描述想要的产品画面 / 场景 / 镜头，可点「AI 生成画面」自动生成，也可手动编辑",
    scenePromptHint: "画面与口播已解耦：此处只描述画面，不影响配音文案",
    // 照片 / AI 图
    modePhoto: "照片 / AI 图",
    photoTitle: "照片 / AI 图",
    photoSubtitle: "一句话生成图片，或上传参考图换背景 / 修图",
    photoPromptLabel: "提示词",
    photoPromptPlaceholder: "描述想要的图片，如：白色大理石台面上的香水瓶，柔光氛围，高级质感",
    photoPromptRequired: "请先输入提示词",
    photoRefLabel: "参考图（可选）",
    photoRefUpload: "上传参考图（JPG / PNG / WebP，≤10MB）",
    photoRefPreviewAlt: "参考图预览",
    photoRefHint: "上传参考图做换背景 / 修图；留空则纯文生图",
    photoSizeLabel: "尺寸",
    photoQualityLabel: "质量",
    photoQuality: { low: "低", medium: "中", high: "高" },
    photoQualityHint: "质量越高，图片越精细、消耗积分越多",
    photoResultAlt: "生成的图片"
  },
  confirm: {
    title: "确定生成",
    estimating: "估算中…",
    estimatePrefix: "预计消耗 ",
    estimateSuffix: " 积分",
    estimateNote: "按实际生成时长结算",
    estimateUnavailable: "暂无法预估，按实际结算",
    warning: "确定生成即会消耗积分，生成过程中无法取消！",
    confirm: "确定",
    confirming: "提交中…",
    cancel: "取消"
  },
  errors: {
    quota: "额度不足，无法生成，请充值或精简任务",
    uploadTooLarge: "图片过大，请控制在 10MB 以内",
    uploadType: "仅支持 JPG / PNG / WebP 图片",
    network: "网络连接失败，请检查后端服务是否在线",
    generic: "操作失败，请重试"
  },
  tasks: {
    title: "生成任务",
    empty: "暂无任务，输入主题开始生成。",
    retry: "重试",
    retryUnavailable: "请到工作台重新发起",
    open: "查看详情",
    moreInHistory: "更多任务见下方「历史生成」"
  },
  history: {
    title: "历史生成",
    tabAvatar: "数字人视频历史",
    tabEcom: "电商视频历史",
    tabPhoto: "照片历史",
    empty: "暂无历史记录",
    loading: "加载中…",
    error: "加载失败，请重试",
    retry: "重试",
    loadMore: "加载更多"
  },
  detail: { notFound: "视频不存在或无权访问", back: "返回", download: "下载 MP4", downloadImage: "下载图片" },
  status: { queued: "排队中", failed: "失败", done: "已完成" }
} as const;
