export const copy = {
  common: { cancel: "取消", processing: "处理中…" },
  // 侧边栏导航（BATCH-PROD-UI-0001-FIX3）
  nav: { comingSoon: "即将上线" },
  // 板块「即将上线」占位（UI-COMINGSOON-TENANT-RENAME-0001）—— 导航后缀 + 统一友好占位页
  comingSoon: {
    navSuffix: "（即将上线）",
    title: "该功能即将上线",
    desc: "敬请期待，我们正在加紧打造这一功能。",
    back: "返回工作台"
  },
  // 登录 / 注册（AUTH-UI-0001）—— 暖金玻璃；「用户名」口径与后端 tenant_slug 对齐
  auth: {
    // 登录
    loginTitle: "登录控制台",
    loginSubmit: "登录",
    loginSubmitting: "登录中…",
    loginNoAccount: "没有账号？",
    loginToRegister: "去注册",
    loginFailed: "登录失败，请重试。",
    // 注册
    registerTitle: "创建账号",
    registerSubtitle: "注册即可体验全部模块",
    registerSubmit: "注册",
    registerSubmitting: "注册中…",
    registerHasAccount: "已有账号？",
    registerToLogin: "去登录",
    // 字段（登录/注册共用）
    usernameLabel: "用户名",
    usernamePlaceholder: "huading",
    usernameHint: "小写字母、数字、连字符，2–80 位",
    teamNameLabel: "团队 / 公司名称",
    teamNamePlaceholder: "华鼎科技",
    emailLabel: "邮箱",
    emailPlaceholder: "you@example.com",
    passwordLabel: "密码",
    passwordHint: "至少 8 位",
    fullNameLabel: "姓名（选填）",
    fullNamePlaceholder: "你的姓名",
    // 客户端校验（friendly 中文；对齐 BE 规则，提交前拦截）
    errUsername: "用户名只能用小写字母、数字、连字符，且需 2–80 位",
    errTeamName: "请填写团队 / 公司名称（不超过 200 字）",
    errEmail: "请输入有效邮箱地址",
    errPassword: "密码需 8–128 位",
    errFullName: "姓名不超过 200 字",
    // 服务端错误映射（不泄露原始异常串）
    errSlugTaken: "该用户名已被占用，请换一个",
    errRegisterFailed: "注册失败，请稍后重试。"
  },
  // 管理员数据看板（ANALYTICS-UI-0001）
  analytics: {
    pageTitle: "数据看板",
    pageSubtitle: "管理员专属 · 全用户用量、成本与趋势总览",
    // 日期区间
    rangeLabel: "日期区间",
    rangeFrom: "起",
    rangeTo: "止",
    preset7: "近 7 天",
    preset30: "近 30 天",
    preset90: "近 90 天",
    rangeInvalid: "起始日期不得晚于结束日期",
    // 概览卡
    ovCredits: "总消耗积分",
    ovCost: "总成本",
    ovTasks: "任务量",
    ovTasksHint: "成功 + 失败",
    ovSuccess: "成功",
    ovFailed: "失败",
    ovTenants: "用户数",
    ovReserved: "预留积分",
    ovReservedHintAll: (n: number) => `全 ${n} 用户合计 · 与已消耗分列`,
    ovReservedHintTop: (n: number) => `消耗榜前 ${n} 用户 · 与已消耗分列`,
    // 用户排行表（数据模型仍为 tenant，仅展示文案改「用户」）
    tenantTitle: "用户排行",
    colTenant: "用户",
    colCredits: "消耗积分",
    colCost: "成本",
    colTasks: "任务量",
    colSuccessRate: "成功率",
    colBalance: "余额（总 / 已用 / 预留 / 剩余）",
    balTotal: "总",
    balUsed: "已用",
    balReserved: "预留",
    balRemaining: "剩余",
    sortAsc: "升序",
    sortDesc: "降序",
    // 分页
    pageRange: (from: number, to: number, total: number) => `第 ${from}–${to} / 共 ${total}`,
    prevPage: "上一页",
    nextPage: "下一页",
    // 按功能/模型
    providerTitle: "按功能 / 模型拆分",
    colProvider: "功能 / 模型",
    colBillingCount: "计费笔数", // ⚠️ 非「任务量」：count(UsageRecord)，含文案/图片等无 VideoTask 的记录
    billingCountHint: "计费笔数 = 计费记录条数（覆盖文案 / 图片等无视频任务的功能），非视频任务数",
    colShare: "占比",
    // 趋势图
    trendTitle: "趋势",
    granDay: "按日",
    granWeek: "按周",
    metricCredits: "积分",
    metricCost: "成本",
    metricTasks: "笔数",
    trendSummary: (metric: string, n: number) => `${metric}趋势，共 ${n} 个数据点`,
    // 通用态
    loading: "加载中…",
    error: "加载失败，请重试",
    retry: "重试",
    empty: "该区间暂无数据",
    // 非管理员 403
    forbiddenTitle: "无权限访问",
    forbiddenDesc: "数据看板仅管理员可见。",
    forbiddenBack: "返回工作台"
  },
  workbench: {
    topicLabel: "视频主题",
    topicPlaceholder: "输入一句话主题，如：三分钟看懂咖啡的起源",
    scriptLabel: "AI 文案（可编辑）",
    regenerate: "重写文案",
    avatarLabel: "数字人形象",
    upload: "上传形象图（JPG / PNG / WebP，≤10MB）",
    voiceLabel: "音色",
    more: "更多设置",
    speed: "语速",
    aspectLocked: "9:16 竖屏（锁定）",
    subtitleLocked: "字幕已开启（锁定）",
    generate: "生成视频",
    generatePhoto: "生成图片",
    scriptTooLong: (s: number) => `预计 ${s}s，将截断到 60s，建议精简文案`,
    // 生成模式切换（数字人口播 / 电商带货）
    modeGroupLabel: "生成模式",
    modeAvatar: "数字人口播",
    modeEcom: "电商带货",
    aspectBadge: "竖屏 9:16",
    avatarPreviewAlt: "形象预览",
    // 数字人形象来源：照片 / 本人出镜视频二选一（AVATAR-VIDEO-SOURCE-UI-0001）
    avatarSourceLabel: "数字人形象来源",
    sourcePhoto: "照片",
    sourceVideo: "本人出镜视频",
    videoUpload: "上传 MP4 本人出镜视频（3–10 秒）",
    videoHint: "MP4，3–10 秒，360p–1080p，单人正脸出镜效果最佳",
    videoPreviewAlt: "视频预览",
    removeVideo: "移除视频",
    videoValidating: "校验视频中…",
    videoReady: "已上传，可生成",
    videoUploading: "上传中…",
    videoUploadFailed: "上传失败",
    // 电商带货（图生视频 i2v）表单
    ecomTitle: "电商带货视频",
    ecomSubtitle: "上传产品图、输入卖点，AI 一键生成带货短片",
    ecomTopicLabel: "产品卖点 / 主题",
    ecomTopicPlaceholder: "输入产品卖点，如：316 不锈钢保温杯，24 小时持续锁温",
    ecomTopicRequired: "请先输入产品卖点",
    ecomImageRequired: "请上传产品图后再生成",
    productImageLabel: "产品图（必填）",
    productImageUpload: "上传产品图（JPG / PNG / WebP，≤10MB）",
    productImagePreviewAlt: "产品图预览",
    // 电商带货：视频时长选择器
    durationLabel: "视频时长",
    durationLabelAligned: "视频时长（与文案、字幕一致）",
    durationSeconds: (s: number) => `${s} 秒`,
    durationCustom: "自定义",
    durationCustomLabel: "自定义时长（秒）",
    durationCustomPlaceholder: "5–120",
    durationRange: "请输入 5–120 秒",
    durationHint: "时长越长，生成越慢、消耗额度越多",
    // 文案/画面解耦（电商带货）
    ecomScriptLabel: "AI 口播文案（仅配音）",
    scenePromptLabel: "画面提示词",
    scenePromptGenerate: "AI 生成画面",
    scenePromptPlaceholder: "描述想要的产品画面 / 场景 / 镜头，可点「AI 生成画面」自动生成，也可手动编辑",
    scenePromptHint: "画面与口播已解耦：此处只描述画面，不影响配音文案",
    // 图片生成 / 修改（mode 值仍为 photo，仅显示文案）
    modePhoto: "图片生成 / 修改",
    photoTitle: "图片生成 / 修改",
    photoSubtitle: "一句话生成图片，或上传参考图换背景 / 修图",
    photoPromptLabel: "提示词",
    photoPromptPlaceholder: "描述想要的图片，如：白色大理石台面上的香水瓶，柔光氛围，高级质感",
    photoPromptRequired: "请先输入提示词",
    photoRefLabel: "参考图（可选）",
    photoRefUpload: "上传参考图（JPG / PNG / WebP，≤10MB）",
    photoRefPreviewAlt: "参考图预览",
    photoRefHint: "上传参考图做换背景 / 修图；留空则纯文生图",
    photoResultAlt: "生成的图片",
    // 画面比例（IMAGE-ASPECT-RATIO-UI-0001）——替代旧「尺寸 / 质量」下拉；8 定比 + 自适应，默认 1:1
    aspectLabel: "画面比例",
    aspectAuto: "自适应",
    aspectAutoHint: "自适应：有输入图按输入图比例输出，无输入图默认 1:1",
    // 文案仿写 + 标题/话题生成（mode: copywriting）
    modeCopywriting: "文案仿写",
    copyTitle: "文案仿写",
    copySubtitle: "粘贴参考文案，AI 改写并生成标题、话题",
    copySourceLabel: "参考文案",
    copySourcePlaceholder: "粘贴你有权使用的参考文案，AI 将据此改写",
    copySourceRequired: "请先粘贴参考文案",
    copyModeLabel: "改写模式",
    copyModeSmart: "智能",
    copyModeCustom: "自定义",
    copyModeAuto: "自动多版",
    copyInstructionLabel: "自定义指令",
    copyInstructionPlaceholder: "如：更口语、更简短、换高端风格",
    copyInstructionRequired: "请填写自定义改写指令",
    copyCountLabel: "候选数量",
    copyPlatformLabel: "目标平台（可选）",
    copyPlatformAny: "不限",
    copyPlatformDouyin: "抖音",
    copyPlatformXiaohongshu: "小红书",
    copyCompliance: "请确保你有权使用与改写所参考的文案",
    copyGenerate: "生成文案",
    copyGenerating: "生成中…",
    copyResultLabel: "改写文案（可编辑）",
    copyCandidatesLabel: "候选文案（点击选用）",
    copyTitlesLabel: "标题候选（点击复制）",
    copyTopicsLabel: "话题候选（点击复制）",
    copyEmptyTitles: "本次未生成标题候选",
    copyEmptyTopics: "本次未生成话题候选",
    copyCopy: "复制",
    copyCopied: "已复制",
    copySave: "保存到历史",
    copySaving: "保存中…",
    copySaved: "已保存",
    copyUseInAvatar: "用此文案 · 数字人口播",
    copyUseInEcom: "用此文案 · 电商带货",
    // 字幕样式（口播生产力增强 ORAL-PROD-UI-0001）；不选 = 默认烧入（不回归 0001）
    subtitleStyleLabel: "字幕样式（可选）",
    subtitleStyleHint: "不选用默认烧入样式；选预设后可微调字号 / 颜色 / 位置",
    subtitleStyleNone: "跟随默认",
    subtitleFontSizeLabel: "字号",
    subtitleColorLabel: "颜色",
    subtitlePositionLabel: "位置",
    subtitlePositionTop: "顶部",
    subtitlePositionCenter: "居中",
    subtitlePositionBottom: "底部",
    subtitleFontSizeRange: "字号需在 16–96",
    subtitlePreviewSample: "字幕预览示例文本",
    // 电商图 / 白底图抠图 (ECOM-IMG-UI-0001)
    modeEcomImage: "电商图",
    ecomCutoutTitle: "白底图 / 抠图",
    ecomCutoutSubtitle: "上传商品图，抠出商品换白底或透明底；支持批量",
    ecomModeSingle: "单张",
    ecomModeBatch: "批量",
    ecomBgLabel: "背景",
    ecomBgWhite: "白底",
    ecomBgTransparent: "透明底",
    ecomUploadLabel: "商品图",
    ecomUploadBatchLabel: "商品图（可多选，最多 20 张）",
    ecomUploadRequired: "请先上传商品图",
    ecomGenerate: "生成",
    ecomGenerating: "生成中…",
    ecomResultsLabel: "结果",
    ecomDownload: "下载",
    ecomDownloadAll: "批量下载",
    ecomBatchOverLimit: "批量最多 20 张，超出部分未添加",
    removeImage: "移除图片",
    // 电商图 · AI 模特 (ECOM-MODEL-UI-0001) — 子工具切换 + 模特偏好
    ecomSubToolLabel: "电商图工具",
    ecomSubToolCutout: "白底图",
    ecomSubToolModel: "AI 模特",
    ecomSubToolPoster: "营销海报", // 已下线（ECOM-REPLICATE-UI-0001）——保留键供 inert adapter/mock，不再入 SUBTOOLS
    ecomSubToolDetail: "电商详情图",
    ecomModeGroupLabel: "生成方式",
    ecomModelTitle: "AI 模特",
    ecomModelSubtitle: "上传商品图，AI 生成上身模特展示图；支持批量",
    ecomGenderLabel: "模特性别",
    ecomGenderFemale: "女",
    ecomGenderMale: "男",
    ecomGenderAny: "不限",
    ecomStyleLabel: "风格预设",
    ecomStyleLoading: "加载风格预设…",
    ecomStyleError: "风格预设加载失败，请重试",
    ecomCustomLabel: "自定义补充（可选）",
    ecomCustomPlaceholder: "补充场景 / 姿态 / 氛围，如：暖光、街头、微笑站姿（≤200 字）",
    ecomModelCompliance: "模特图为 AI 生成，商品以实物为准",
    // 电商图 · 营销海报 (ECOM-POSTER-UI-0001)
    ecomPosterTitle: "营销海报",
    ecomPosterSubtitle: "上传商品图，套版式 + 标题文案，一键生成营销海报；支持批量",
    ecomTemplateLabel: "版式预设",
    ecomTemplateLoading: "加载版式预设…",
    ecomTemplateError: "版式预设加载失败，请重试",
    ecomPosterTitleLabel: "标题（可选）",
    ecomPosterTitlePlaceholder: "海报主标题，如：年中大促 全场 5 折",
    ecomPosterTaglineLabel: "自定义一行（可选）",
    ecomPosterTaglinePlaceholder: "副标题 / 卖点一行，如：限时 3 天 错过再等一年",
    // 电商详情图·强制复刻向导 (ECOM-REPLICATE-UI-0001)
    ecomDetailTitle: "电商详情图 · 复刻生成",
    ecomDetailSubtitle: "上传参考图 + 商品图，AI 按参考图强制复刻，只换商品与文案（相似度 ≥80%）",
    ecomDetailModeLabel: "出图模式",
    ecomDetailModeMain: "主图（5 张）",
    ecomDetailModeDetail: "详情页（12 张）",
    ecomDetailRefLabel: "参考图（复刻模板，1+ 张）",
    ecomDetailRefUpload: "上传参考图（JPG / PNG / WebP，≤10MB）",
    ecomDetailProductLabel: "商品图（唯一商品依据，1+ 张）",
    ecomDetailProductUpload: "上传商品图（JPG / PNG / WebP，≤10MB）",
    ecomDetailInfoLabel: "商品信息",
    ecomDetailInfoPlaceholder: "品类 / 材质 / 规格等（只用你提供的信息，AI 不补全材质、认证、功效、销量）",
    ecomDetailPointsLabel: "核心卖点",
    ecomDetailPointPlaceholder: "一条卖点，如：316 不锈钢，24 小时持续锁温",
    ecomDetailAddPoint: "添加卖点",
    ecomDetailRemovePoint: "删除该卖点",
    ecomDetailPlan: "生成规划表",
    ecomDetailPlanning: "分析参考图 · 生成规划中…",
    // 规划表确认（§10 列 + 整套总价 + 扣费确认）
    ecomPlanTitle: "生成规划（确认后按此复刻，仅确认一次）",
    ecomPlanColPage: "页码",
    ecomPlanColTheme: "页面主题",
    ecomPlanColSize: "尺寸",
    ecomPlanColPrompt: "生成要点",
    ecomPlanColOutput: "最终输出",
    ecomPlanNoCrop: "原图不裁剪",
    // BE plan.outputs[].theme 为机器枚举键（backend _MAIN_THEMES/_DETAIL_THEMES）；本地化展示，未知键原样透出。
    ecomReplicateTheme: (theme: string) =>
      (({
        layout_match: "版式复刻",
        color_match: "配色复刻",
        campaign_match: "营销卖点",
        social_match: "种草风格",
        white_background: "纯白底图",
        hero: "首屏主视觉",
        material: "材质细节",
        function: "功能展示",
        size: "尺寸规格",
        scenario: "使用场景",
        detail: "细节特写",
        comparison: "对比展示",
        packing: "包装展示",
        care: "养护说明",
        selling_point: "核心卖点",
        closing: "信任收尾"
      }) as Record<string, string>)[theme] ?? theme,
    ecomPlanTotalPrice: (credits: number) => `整套预计 ${credits} 积分`,
    ecomPlanConfirm: "确认并生成",
    ecomPlanBack: "返回修改",
    ecomChargeTitle: "确认扣费生成整套？",
    ecomChargeMessage: (credits: number) =>
      `将一次性扣除 ${credits} 积分生成整套图片，确认后开始复刻；质检失败的单张会自动重试、不重复扣费。`,
    ecomChargeConfirm: "确认扣费生成",
    // 生成中（禁分批展示，全部完成才一次性展示）
    ecomGenTitle: "复刻生成中",
    ecomGenProgress: (done: number, total: number) => `已完成 ${done} / ${total}，全部完成后一次性展示`,
    ecomGenWait: "整套生成中，请稍候…全部完成后统一展示",
    // 轮询瞬时失败（500/离线）：不放弃整套（已扣费、后端仍在生成），软提示 + 下一拍自动重试
    ecomGenRetrying: "网络波动，正在重试…整套仍在后端生成，请勿离开",
    // 结果（一次性 + 原始尺寸 + 平台建议 §18 + 下载原图 + 单张重试）
    ecomResultTitle: "复刻结果（整套）",
    ecomResultPageNo: (n: number) => `第 ${n} 张`,
    ecomResultSizeMain: (actual: string) =>
      `当前图片为 AI 原始输出尺寸：${actual}。平台建议主图尺寸：800x800。系统未自动裁剪，请下载后按平台要求自行裁剪或上传时调整。`,
    ecomResultSizeDetail: (actual: string) =>
      `当前图片为 AI 原始输出尺寸：${actual}。平台建议详情页尺寸：750x1000。系统未自动裁剪，请下载后按平台要求自行裁剪或上传时调整。`,
    // actual_dimensions 缺失（后端未回）→ 不把请求尺寸冒充实际输出尺寸（原图尺寸透明红线）
    ecomResultSizeUnknown: "AI 原图已生成，原始尺寸以下载文件为准。系统未自动裁剪，请下载后按平台要求自行调整。",
    ecomResultDownload: "下载原图",
    ecomResultDownloadUnavailable: "原图暂不可用",
    ecomResultRetry: "重试该张",
    ecomResultRetrying: "重试中…",
    ecomResultFailed: "该张生成失败",
    ecomResultPartialHint: "部分图片生成失败，可对失败图单张重试（不重复扣费）",
    ecomResultAllFailed: "整套生成失败，可返回重新发起；已扣费问题请联系客服。",
    ecomResultPreviewAlt: (n: number) => `复刻图第 ${n} 张`,
    // 提示词反推 第7模式 (REVERSE-PROMPT-UI-0001) — 上传图片反推提示词 + 一键带入
    modeReverse: "提示词反推",
    // 视频生成 第6模式 (VIDEOGEN-UI-0001) — 多参考图 + 不限 prompt + 时长/分辨率 + BGM
    modeVideoGen: "视频生成",
    vgTitle: "视频生成",
    vgSubtitle: "多张参考图 + 提示词，生成创意短视频；可加背景音乐",
    vgRefImagesLabel: "参考图（最多 9 张）",
    vgRefImagesUpload: "添加参考图",
    vgRefImagesRequired: "请至少上传 1 张参考图",
    vgRefOverLimit: "最多 9 张参考图，超出部分未添加",
    // 名词中性 + 随上限动态（供复用 picker 如电商详情图·商品图 max=4，避免误显「参考图」「9 张」）
    refImagesOverLimit: (max: number) => `最多 ${max} 张，超出部分未添加`,
    vgPromptLabel: "提示词",
    vgPromptPlaceholder: "描述你想要的画面、风格、运镜、氛围…（不限字数）",
    vgPromptRequired: "请填写提示词",
    vgDurationLabel: "时长",
    vgResolutionLabel: "分辨率",
    vgResolutionHint: "更高分辨率更清晰，生成更慢、消耗更多",
    vgBgmLabel: "背景音乐",
    vgBgmNone: "无",
    vgBgmUpload: "上传",
    vgBgmLibrary: "配乐库",
    vgBgmUploadBtn: "上传音乐文件",
    vgBgmUploading: "上传中…",
    vgBgmUploaded: "已添加音乐，可重新上传替换",
    vgBgmUploadedPreview: "试听已上传的背景音乐",
    vgBgmRemove: "移除音乐",
    vgBgmLibraryLoading: "加载配乐库…",
    vgBgmLibraryError: "配乐库加载失败，请重试",
    vgBgmLibraryEmpty: "暂无可用配乐",
    vgBgmSelect: "选用",
    vgBgmSelected: "已选用",
    vgBgmPreviewLabel: (name: string) => `试听 ${name}`,
    vgGenerating: "生成中…",
    // BGM 波形播放器 (BGM-WAVEFORM-UI-0001)
    wfPlay: "播放",
    wfPause: "暂停",
    wfSeek: "拖动或点击波形跳转播放位置",
    wfLoading: "加载波形…"
  },
  confirm: {
    title: "确定生成",
    estimating: "估算中…",
    estimatePrefix: "预计消耗 ",
    estimateSuffix: " 积分",
    estimateNote: "按实际生成时长结算",
    estimateUnavailable: "暂无法预估，按实际结算",
    warning: "确定生成即会消耗积分，生成过程中无法取消！",
    confirm: "确定",
    confirming: "提交中…",
    cancel: "取消"
  },
  errors: {
    quota: "额度不足，无法生成，请充值或精简任务",
    uploadTooLarge: "图片过大，请控制在 10MB 以内",
    uploadType: "仅支持 JPG / PNG / WebP 图片",
    network: "网络连接失败，请检查后端服务是否在线",
    generic: "操作失败，请重试",
    // 数字人出镜视频客户端预检（AVATAR-VIDEO-SOURCE-UI-0001，MP4/≤10s/360p–1080p）
    videoType: "仅支持 MP4 视频",
    videoTooLarge: "视频过大，请控制在 200MB 以内",
    videoTooLong: "请上传 3–10 秒的单人出镜视频",
    reverseVideoDuration: "请上传 1–60 秒的视频",
    reverseVideoFailed: "视频反推失败，请稍后重试",
    videoResolution: "视频分辨率需在 360p–1080p",
    videoUnreadable: "无法读取视频信息，请换一个 MP4 文件",
    // 电商详情图复刻·客户端校验（ECOM-REPLICATE-UI-0001）
    ecomDetailNeedMode: "请选择生成模式：主图 / 详情页",
    ecomDetailNeedRef: "请上传参考图（至少 1 张）",
    ecomDetailNeedProduct: "请上传商品图（至少 1 张）",
    ecomDetailNeedInfo: "请填写商品信息",
    ecomDetailNeedPoint: "请至少填写 1 条核心卖点",
    ecomDetailFailed: "生成规划失败，请稍后重试",
    ecomDetailGenFailed: "生成失败，请稍后重试",
    // 后端二次校验专属码（FE-INTEGRATION-0001；前端预检读不到编码，回显后端码时用）
    videoCodec: "视频编码需为 H.264，请用常见工具重新导出 MP4",
    videoAudioCodec: "视频音轨需为 AAC，请用常见工具重新导出 MP4",
    videoAssetLost: "视频资源已失效，请重新上传",
    // 商品表批量(seedance_i2v)缺音色 → 后端 422(voice_id is required) 的中文映射
    voiceRequired: "请选择音色",
    // 图片生成错误（按后端 error_code 映射；见 friendlyImageError）
    imageModeration: "内容被 AI 安全系统拦截，请调整描述后重试（避免敏感或人体性暗示内容）",
    imageConnection: "网络连接失败，请检查代理 / 网络后重试",
    imageInvalid: "生成参数有误，请调整尺寸 / 质量或描述后重试",
    imageGeneric: "图片生成失败，请重试",
    // 抠图透明底专属（IMAGE_ALPHA_MISSING）：可操作文案，不落通用兜底
    imageAlphaMissing: "透明底生成失败：未返回透明像素，请重试或改用白底",
    // 视频失败友好映射（VIDEO-ERR-MAP-UI，与后端 VIDEO-ERR-MAP-BE 共用错误码）——绝不回落裸 error_message
    videoInsufficientBalance: "余额不足，无法生成，请充值后重试",
    videoTimeout: "生成超时，请稍后重试",
    videoConnection: "网络异常，请检查网络后重试",
    videoGeneric: "视频生成失败，请重试",
    // 批量电商行参考图下载失败（BATCH_IMAGE_DOWNLOAD_FAILED，可操作）——批量视频失败面复用视频友好映射
    batchImageDownloadFailed: "参考图下载失败，请改用本地上传后重试",
    // 品牌音色音频上传/录音 (BRAND-VOICE-UI-0001)
    audioType: "仅支持 WAV / MP3 / M4A 音频",
    audioTooLarge: "音频过大，请控制在 20MB 以内",
    audioTooShort: "音频时长需至少 5 秒，请重录或换更长的音频",
    // 提示词反推失败（REVERSE-PROMPT-UI-0001）——通用兜底，绝不回落裸 error_message/技术串
    reverseFailed: "提示词反推失败，请稍后重试"
  },
  // 提示词反推 · 图片 (REVERSE-PROMPT-UI-0001) —— 上传图片 → 反推可复用提示词 → 一键带入 4 模块
  reverse: {
    title: "提示词反推 · 图片",
    subtitle: "上传一张图片，AI 反推可复用的提示词，并可一键带入各生成模块",
    upload: "上传图片",
    uploadHint: "支持 JPG / PNG / WebP，≤10MB；仅用于本次反推参考",
    reupload: "换一张",
    // 输出语言/细节度不进请求（BE extra="forbid"，且输出本就同时给 zh+en）——面板已移除，仅保留目标格式只读展示。
    targetLabel: "目标格式",
    targetSeedance: "Seedance 2.0",
    analyze: "开始反推",
    analyzing: "AI 正在反推提示词…",
    resultTitle: "反推结果",
    // 近似重建红线（BE 未随 result 下发 disclaimer 时的前端兜底文案）
    disclaimer: "AI 依据画面近似重建提示词，仅供二次创作参考，不保证完全复刻原素材。",
    confidenceLabel: "置信度",
    blockPromptZh: "中文提示词",
    blockPromptEn: "英文提示词",
    blockNegative: "反向提示词",
    blockSubject: "主体",
    blockScene: "场景",
    blockComposition: "构图",
    blockCamera: "镜头",
    blockLighting: "光线",
    blockStyle: "风格标签",
    blockMotion: "运动提示",
    blockSelling: "电商卖点",
    blockText: "画面文字（仅识别，不执行）",
    copy: "复制",
    copied: "已复制",
    save: "保存到历史",
    saving: "保存中…",
    saved: "已保存",
    regenerate: "重新反推",
    regenerating: "反推中…",
    applyTitle: "带入生成",
    applyHint: "选一个模块，把反推结果预填进去继续生成",
    applyAvatar: "带入 · 数字人口播",
    applyEcomVideo: "带入 · 电商带货",
    applyVideoGen: "带入 · 视频生成",
    applyPhoto: "带入 · 图片生成",
    applyEcomModel: "带入 · AI 模特",
    applyEcomPoster: "带入 · 营销海报",
    applyUnavailable: "该模块暂无可带入内容",
    // 视频反推（VIDEO-REVERSE-PROMPT-UI-0001）—— 一个入口两模式（图片同步 / 视频异步 + 计费门）
    sourceLabel: "反推来源",
    sourceImage: "图片",
    sourceVideo: "视频",
    videoTitle: "提示词反推 · 视频",
    videoSubtitle: "上传一段视频，AI 分析分镜与节奏并反推可复用的提示词",
    videoUpload: "上传视频",
    videoUploadHint: "MP4（H.264），≤200MB，1–60 秒；音轨可选（不强制）",
    videoReupload: "换一个视频",
    videoValidating: "校验视频中…",
    videoReady: "已上传，可反推",
    videoUploading: "上传中…",
    videoAnalyze: "反推视频提示词",
    videoAnalyzing: "AI 正在分析视频并反推…",
    videoPollRetrying: "网络波动，正在重试…视频仍在后端分析，请稍候",
    // 计费门（视频反推 100 积分/次）
    videoChargeTitle: "确认扣费反推视频？",
    videoChargeMessage: (credits: number) => `视频反推将一次性扣除 ${credits} 积分（分析分镜 + 生成提示词）；确认后开始，取消不扣费。`,
    videoChargeConfirm: "确认扣费反推",
    videoChargeBadge: (credits: number) => `${credits} 积分 / 次`,
    // 视频分析展示（在提示词结果之上）
    vaTitle: "视频分析",
    vaDuration: "时长",
    vaDurationValue: (sec: number) => `${sec} 秒`,
    vaPacing: "节奏",
    // pacing 枚举 → 中文显示（BE slow|medium|fast|variable，不显裸英文）
    vaPacingLabel: { slow: "慢", medium: "中", fast: "快", variable: "可变" } as Record<string, string>,
    vaShotList: "分镜列表",
    vaShot: (n: number) => `镜头 ${n}`,
    vaShotRange: (start: number, end: number) => `${start}–${end}s`,
    vaShotCamera: "运镜",
    vaShotMotion: "动作",
    vaShotTransition: "转场",
    vaAudioTranscript: "音频转写",
    vaBgmStyle: "背景音乐风格",
    vaNotEnabled: "未启用（一期）"
  },
  tasks: {
    title: "生成任务",
    empty: "暂无任务，输入主题开始生成。",
    retry: "重试",
    retryUnavailable: "请到工作台重新发起",
    open: "查看详情",
    moreInHistory: "更多任务见下方「历史生成」"
  },
  history: {
    title: "历史生成",
    tabAvatar: "数字人视频历史",
    tabEcom: "电商视频历史",
    tabVideoGen: "视频生成历史",
    tabPhoto: "图片历史",
    tabCopy: "文案历史",
    empty: "暂无历史记录",
    loading: "加载中…",
    error: "加载失败，请重试",
    retry: "重试",
    loadMore: "加载更多",
    filterAllImages: "全部图片",
    filterCovers: "仅封面",
    deleteItem: "删除",
    clearAll: "清空",
    deleteConfirmTitle: "删除这条记录？",
    deleteConfirmHard: "将永久删除，不可恢复。",
    deleteConfirmSoft: "将从历史移除（可恢复）。",
    deleteConfirmBtn: "确认删除",
    clearConfirmTitle: "清空该历史？",
    clearConfirmHard: "将永久删除此模块全部记录，不可恢复。",
    clearConfirmPhotoHard: "将清空全部图片（含封面），硬删不可恢复；不受当前「仅封面」筛选影响（始终删除全部图片）。",
    clearConfirmSoft: "将清空此模块全部草稿（可恢复）。",
    clearConfirmBtn: "确认清空",
    deleteFailed: "删除失败，请重试",
    clearFailed: "清空失败，请重试"
  },
  // 图片历史·统一模块 (HISTORY-UI-0001) — 独立页 /history，4 tab（归一 category）。
  historyImages: {
    navEntry: "图片历史",
    pageTitle: "图片历史",
    pageSubtitle: "查看历史生成的图片，重开整套并下载原图",
    tabImageGen: "图片生成/修改",
    tabEcomWhite: "电商·白底图",
    tabEcomModel: "电商·模特图",
    tabEcomDetail: "电商·详情图",
    empty: "该分类暂无历史记录",
    emptyHint: "生成的图片会在这里归档，可随时重开整套、下载原图",
    loading: "加载中…",
    error: "加载失败，请重试",
    retry: "重试",
    loadMore: "加载更多",
    itemCount: (n: number) => `${n} 张`,
    // 状态徽标（归一 completed/partial_failed/failed/ready）
    statusCompleted: "已完成",
    statusPartial: "部分失败",
    statusFailed: "失败",
    statusReady: "已就绪",
    // 重开整套弹窗
    setTitle: "整套图片",
    setLoading: "加载整套图片中…",
    setError: "整套加载失败，请重试",
    setEmpty: "该记录暂无可展示的图片",
    setPartialHint: "本套部分图片生成失败（缺失项不可下载）",
    setPageNo: (n: number) => `第 ${n} 张`,
    previewAlt: (n: number) => `历史图片第 ${n} 张`,
    // 原图红线（下载原始 bytes、显示原始尺寸、缺失禁用）
    sizeLabel: (dims: string) => `原始尺寸：${dims}（下载为原图，未裁剪）`,
    sizeUnknown: "原图尺寸以下载文件为准（未裁剪）",
    download: "下载原图",
    downloadUnavailable: "原图暂不可用",
    close: "关闭"
  },
  detail: { notFound: "视频不存在或无权访问", back: "返回", download: "下载 MP4", downloadImage: "下载图片" },
  status: { queued: "排队中", failed: "失败", done: "已完成", cancelled: "已取消" },
  // 封面制作（口播视频产物附属 ORAL-PROD-UI-0001）
  cover: {
    entry: "做封面",
    title: "制作封面",
    subtitle: "从口播视频抽帧叠标题，或用 AI 生成封面",
    tabFrame: "截帧",
    tabAi: "AI 封面",
    frameLoading: "加载候选帧…",
    frameError: "候选帧加载失败，请重试",
    frameEmpty: "暂无候选帧",
    frameLabel: "选择封面帧",
    titleLabel: "封面标题（可选）",
    titlePlaceholder: "输入封面标题文字，可留空＝纯截帧",
    titleFontSizeLabel: "标题字号",
    titleColorLabel: "标题颜色",
    titlePositionLabel: "标题位置",
    titleFontSizeRange: "字号需在 24–120",
    generateFrame: "生成封面",
    generatingFrame: "生成中…",
    aiPromptLabel: "封面描述",
    aiPromptPlaceholder: "描述想要的封面画面，如：暖光下的咖啡杯特写，高级质感",
    generateAi: "AI 生成封面",
    generatingAi: "生成中…",
    aiPending: "封面生成中，完成后自动展示并存入图片历史…",
    aiDoneNoUrl: "已生成，请到图片历史查看",
    resultAlt: "封面预览",
    download: "下载封面",
    frameSaved: "封面已生成，可下载",
    savedToHistory: "已存入图片历史",
    retry: "重试"
  },
  // 品牌音色 / 声音克隆 (BRAND-VOICE-UI-0001)
  brandVoice: {
    entry: "我的品牌音色",
    pageTitle: "品牌音色",
    pageSubtitle: "录制或上传一段音频，克隆成你的专属口播音色",
    // 创建
    createTitle: "新建品牌音色",
    createSubtitle: "录一段或上传音频 → 试听 → 授权 → 创建",
    recordPrompt: "请用自然的语速朗读：「大家好，欢迎来到我的直播间，今天给大家带来一款超值好物。」",
    recordHint: "在安静环境录制，时长至少 5 秒，吐字清晰效果更好",
    recordStart: "开始录音",
    recordStop: "停止录音",
    recording: "录音中…",
    recordAgain: "重新录制",
    recordPermissionDenied: "麦克风权限被拒绝，请在浏览器允许后重试，或改用上传",
    recordUnsupported: "当前浏览器不支持录音，请改用上传音频",
    orUpload: "或上传音频",
    uploadAudio: "上传音频（WAV / MP3 / M4A，≤20MB）",
    audioReady: "音频已就绪，可试听",
    previewAria: "试听待克隆音频",
    removeAudio: "移除音频",
    nameLabel: "音色名称",
    namePlaceholder: "给你的品牌音色起个名字，如：我的主播音",
    consentLabel: "我已获得被克隆人的授权，并知悉生成内容为 AI 深度合成，将合法合规使用",
    consentRequired: "请先勾选授权声明后再创建",
    complianceHint: "未经授权克隆他人声音可能违法；请确保已获授权，生成内容为 AI 深度合成",
    create: "创建品牌音色",
    creating: "创建中…",
    createNeedAudio: "请先录制或上传一段音频",
    createNeedName: "请填写音色名称",
    // 克隆通路选择（BRAND-VOICE-PICKER-UI-0001 范围4，文案用户定稿）
    providerSectionLabel: "克隆通路",
    providerCosyTitle: "免费开通私人专属音色",
    providerCosyDesc: "CosyVoice-v3.5-plus · 免费",
    providerDoubaoTitle: "升级版 VIP 永久高端定制音色",
    providerDoubaoDesc: "豆包 · 300 元（30000 积分）",
    chargeConfirmTitle: "确认开通高端定制音色？",
    chargeConfirmMessage: (credits: number) =>
      `将消耗 ${credits} 积分（约 300 元）开通豆包 VIP 永久高端定制音色，确认后立即扣费，克隆结果生成后不可退。`,
    chargeConfirmBtn: "确认扣费开通",
    // 列表
    listTitle: "我的品牌音色",
    listLoading: "加载中…",
    listError: "加载失败，请重试",
    listEmpty: "还没有品牌音色，录制或上传一段音频来创建",
    statusProcessing: "处理中",
    statusReady: "可用",
    statusFailed: "失败",
    processingHint: "声音克隆处理中，完成后即可在口播选用",
    delete: "删除",
    deleteConfirmTitle: "删除该品牌音色？",
    deleteConfirmMessage: "将永久删除，不可恢复；已生成的视频不受影响。",
    deleteConfirmBtn: "确认删除",
    // 口播 picker 分组
    pickerBrandGroup: "我的品牌音色",
    pickerStandardGroup: "系统音色",
    // 「选我的音色」picker（BRAND-VOICE-PICKER-UI-0001）
    pickerBrandLoading: "加载我的音色…",
    pickerBrandEmpty: "还没有品牌音色",
    pickerBrandCreate: "去创建",
    pickerCloning: "复刻中",
    providerDoubao: "豆包",
    providerCosyvoice: "CosyVoice"
  },
  // 深度合成标识设置 (LABEL-UI-0001)
  label: {
    entry: "标识设置",
    pageTitle: "深度合成标识",
    pageSubtitle: "配置显式标识的位置与文案（在生成时开启标识的任务上生效）",
    settingsTitle: "标识水印",
    positionLabel: "标识位置",
    posBr: "右下",
    posBl: "左下",
    posTr: "右上",
    posTl: "左上",
    posBc: "底部居中",
    textLabel: "标识文案",
    textPlaceholder: "如：AI 生成（≤20 字，必填）",
    textRequired: "标识文案不能为空",
    previewLabel: "实时预览",
    // 与任务级开关语义统一(LABEL-TOGGLE-UI-0001)：此页配样式/文案，是否应用由每次生成开关决定
    applyNoticeTitle: "显式标识如何生效",
    applyNoticeHint: "此处仅配置显式标识的位置与文案；是否应用显式标识由每次生成时的「AI 生成标识」开关决定（默认关闭）。",
    save: "保存",
    saving: "保存中…",
    saved: "已保存",
    // 产物处知情提示
    productNotice: "已含 AI 生成标识",
    // AI 生成标识开关（LABEL-TOGGLE-UI-0001）：六大面板统一，默认关；不弹窗不阻断
    toggleLabel: "AI 生成标识",
    toggleHint: "关闭后，发布到抖音/快手等平台请自行完成 AI 内容声明"
  },
  // 发布中心 (PUBLISH-UI-0001)
  publish: {
    entry: "发布",
    pageTitle: "发布中心",
    pageSubtitle: "选平台生成各平台文案，一键复制 / 下载 / 去发布",
    platformLabel: "选择发布平台（可多选）",
    noSourceHint: "从「历史」或成片详情点「发布」进入，选择要发布的产物",
    generateDrafts: "生成各平台草稿",
    generating: "生成中…",
    selectAtLeastOne: "请至少选择一个平台",
    // 草稿卡
    cardTitleLabel: "标题",
    cardTextLabel: "文案",
    cardTopicsLabel: "话题（空格分隔）",
    coverAlt: "封面预览",
    copyText: "一键复制文案",
    copied: "已复制",
    copyFailed: "复制失败，请手动选择文案",
    download: "下载成片",
    goPublish: "去发布",
    goPublishAt: (name: string) => `去${name}发布`,
    markPublished: "标记已发布",
    marking: "标记中…",
    marked: "已发布",
    markFailed: "标记失败，请重试",
    // 记录
    recordsTitle: "发布记录",
    recordsLoading: "加载中…",
    recordsError: "加载失败，请重试",
    recordsEmpty: "暂无发布记录",
    statusDraft: "草稿",
    statusCopied: "已复制",
    statusPublished: "已发布",
    sourceVideo: "视频",
    sourceImage: "图片",
    deleteRecord: "删除",
    deleteConfirmTitle: "删除该发布记录？",
    deleteConfirmMessage: "将从发布记录移除，不影响已发布的内容。",
    deleteConfirmBtn: "确认删除",
    // 平台名（与后端 platforms 接口一致；此处为兜底展示）
    platformDouyin: "抖音",
    platformKuaishou: "快手",
    platformWechat: "视频号",
    platformXiaohongshu: "小红书",
    platformBilibili: "B站"
  },
  // 批量生产中心 (BATCH-PROD-UI-0001)
  batch: {
    pageTitle: "批量生产",
    pageSubtitle: "上传商品表或提示词组，一次批量出片（单批最多 30 条）",
    tabEcom: "商品表",
    tabPrompt: "提示词组",
    // 商品表（入口 A）
    ecomUploadLabel: "上传商品表（Excel / CSV）",
    ecomUploadBtn: "选择文件",
    ecomUploadHint: "列：商品名 / 卖点 / 商品图（URL 或留空后拖入本地图）；每行一条电商带货视频",
    ecomParseError: "表格解析失败，请检查文件格式",
    ecomColProduct: "商品名",
    ecomColSelling: "卖点",
    ecomColImage: "商品图",
    ecomColStatus: "校验",
    ecomRowOk: "就绪",
    ecomRowError: "缺必填",
    ecomErrProductRequired: "商品名必填",
    ecomErrSellingRequired: "卖点必填",
    ecomErrImageRequired: "商品图必填（URL 或上传）",
    ecomEmpty: "请上传商品表以预览",
    ecomHasInvalid: "部分行缺必填项（商品名 / 卖点 / 图），请补全后再生成",
    ecomRowImageUpload: "上传本地图",
    // 提示词组（入口 B）
    promptLabel: "提示词（每行一条，最多 30 条）",
    promptPlaceholder: "每行一条提示词，如：\n赛博城市夜景，霓虹运镜\n春日樱花街道，暖光",
    promptCount: (n: number) => `${n} 条`,
    promptEmpty: "请至少输入 1 条提示词",
    // 逐行配对参考图（BATCH-PROD-UI-0002）
    pairToggleLabel: "逐行配对参考图",
    pairToggleHint: "开启后按顺序为每条提示词各配一张参考图（第 N 行 ↔ 第 N 张）；关闭则参考图整体共用。",
    pairSharedNote: "参考图将应用于本批每一条。",
    pairPreviewTitle: "配对预览（请核对顺序）",
    pairCountMismatch: (prompts: number, images: number) =>
      `参考图数量需与提示词行数一致：当前提示词 ${prompts} 行、参考图 ${images} 张。`,
    pairRowLabel: (n: number) => `第 ${n} 行`,
    pairMissingImage: "缺图",
    // 公共参数
    commonTitle: "公共参数（应用到本批每条）",
    // 超限（真拦截：禁用 + 显式提示，不裁剪）
    overLimitN: (n: number) => `单批最多 30 条，当前 ${n} 条，请删减后再生成`,
    ecomTooLarge: "文件过大（最多 5MB），请精简后重传",
    ecomTooManyRows: "表格行数过多（最多 500 行），请拆分后重传",
    // 预估确认
    estimateTitle: "确认批量生产",
    estimateRows: (n: number) => `共 ${n} 条`,
    estimatePerRow: "单条积分",
    estimateTotal: "预计总积分",
    estimateBalance: "当前余额",
    estimateVoice: "配音音色",
    estimateInsufficient: "余额不足，无法提交本批",
    estimateQueueHint: "1080P 当前高峰可能排队较久",
    estimateConfirm: "确认生成",
    estimateCancel: "取消",
    estimating: "预估中…",
    submitting: "提交中…",
    createFailed: "批次创建失败",
    // 批次列表 + 详情
    listTitle: "批次记录",
    listEmpty: "暂无批次",
    listLoading: "加载中…",
    listError: "加载失败，请重试",
    progressLabel: (done: number, total: number) => `${done}/${total}`,
    statusRunning: "生成中",
    statusCompleted: "已完成",
    statusPartial: "部分失败",
    statusFailed: "失败",
    statusCancelled: "已取消",
    detailTitle: "批次详情",
    rowIndex: (i: number) => `第 ${i + 1} 条`,
    taskRetry: "重试",
    taskRetrying: "重试中…",
    cancelBatch: "取消批次",
    cancelling: "取消中…",
    cancelHint: "仅取消未开始的条目，已在生成的不中断",
    openBatch: "查看进度",
    backToList: "返回列表",
    kindEcom: "商品表",
    kindPrompt: "提示词组"
  },
  // 落地页 (LANDING-ENTRY-UI-0001) —— 文案一字不差取需求冻结 §三（v3 定稿）
  landing: {
    skipToMain: "跳到主要内容",
    brand: "华鼎AI · 短视频引擎",
    navFeatures: "功能",
    navSamples: "样片",
    navSteps: "教学",
    navAria: "落地页导航",
    // 入口两态（右上角）
    login: "登录",
    register: "立即注册",
    avatarAria: "账户菜单",
    menuConsole: "进控制台",
    menuLogout: "退出登录",
    // Hero
    heroBadge: "AI 驱动 · 全自动短视频生产",
    heroTitle: "企业级 AI 短视频工厂",
    heroSub:
      "输入主题、商品或脚本，批量产出符合品牌规范、可直接分发到各平台的成片。数字人口播、电商图、文案、视频，一站式智能生产。",
    ctaRegister: "立即免费注册",
    ctaLogin: "登录控制台",
    // 数据条（冻结 §三※：不用不实的「500+」）
    statModules: "7 大模块",
    statAuto: "全自动生产",
    statDistribute: "多平台分发",
    // 七大生产模块
    modulesTitle: "七大生产模块",
    modulesSub: "一个工作台，覆盖短视频生产全链路",
    modAvatar: "数字人口播",
    modAvatarDesc: "照片或本人出镜视频，一键生成真人口播",
    modVideoGen: "视频生成",
    modVideoGenDesc: "文生视频·图生视频，主题即成片",
    modEcomImage: "电商图",
    modEcomImageDesc: "白底图·模特图·详情图复刻",
    modPhoto: "图片生成·修改",
    modPhotoDesc: "AI 出图，多种画面比例自由选",
    modCopywriting: "文案仿写",
    modCopywritingDesc: "输入爆款，仿写你的品牌话术",
    modEcomVideo: "电商带货",
    modEcomVideoDesc: "商品图一键生成带货短视频",
    modReverse: "提示词反推",
    modReverseDesc: "图片·视频反推可复用提示词",
    modMore: "更多能力持续上线",
    // 效果样片（占位）
    samplesTitle: "效果样片",
    samplesSub: "真实由平台生成（占位，待替换你的样片）",
    sampleAvatar: "口播样片",
    sampleEcomImage: "电商图",
    sampleEcomVideo: "带货视频",
    sampleAiImage: "AI 图",
    samplePlaceholder: "样片占位",
    // 五步上手
    stepsTitle: "五步上手",
    step1: "注册并登录控制台",
    step2: "在工作台选择模块（数字人口播/电商图/文案…）",
    step3: "输入主题或上传素材（商品图、脚本、原视频）",
    step4: "一键生成，实时查看进度",
    step5: "下载原片或直接发布到各平台",
    // 注册 CTA 区
    ctaTitle: "现在开始，把视频生产变成流水线",
    ctaSub: "新用户注册即可体验全部模块",
    // 页脚
    footerCopyright: "© 华鼎 · 企业级 AI 短视频引擎",
    footerIcp: "备案号：占位",
    footerAbout: "关于",
    footerContact: "联系",
    footerTerms: "服务条款"
  }
} as const;
