export const copy = {
  common: { cancel: "取消", processing: "处理中…" },
  workbench: {
    topicLabel: "视频主题",
    topicPlaceholder: "输入一句话主题，如：三分钟看懂咖啡的起源",
    scriptLabel: "AI 文案（可编辑）",
    regenerate: "重写文案",
    avatarLabel: "数字人形象",
    upload: "上传形象图（JPG / PNG / WebP，≤10MB）",
    voiceLabel: "音色",
    more: "更多设置",
    speed: "语速",
    aspectLocked: "9:16 竖屏（锁定）",
    subtitleLocked: "字幕已开启（锁定）",
    generate: "生成视频",
    generatePhoto: "生成图片",
    scriptTooLong: (s: number) => `预计 ${s}s，将截断到 60s，建议精简文案`,
    // 生成模式切换（数字人口播 / 电商带货）
    modeGroupLabel: "生成模式",
    modeAvatar: "数字人口播",
    modeEcom: "电商带货",
    aspectBadge: "竖屏 9:16",
    avatarPreviewAlt: "形象预览",
    // 电商带货（图生视频 i2v）表单
    ecomTitle: "电商带货视频",
    ecomSubtitle: "上传产品图、输入卖点，AI 一键生成带货短片",
    ecomTopicLabel: "产品卖点 / 主题",
    ecomTopicPlaceholder: "输入产品卖点，如：316 不锈钢保温杯，24 小时持续锁温",
    ecomTopicRequired: "请先输入产品卖点",
    ecomImageRequired: "请上传产品图后再生成",
    productImageLabel: "产品图（必填）",
    productImageUpload: "上传产品图（JPG / PNG / WebP，≤10MB）",
    productImagePreviewAlt: "产品图预览",
    // 电商带货：视频时长选择器
    durationLabel: "视频时长",
    durationLabelAligned: "视频时长（与文案、字幕一致）",
    durationSeconds: (s: number) => `${s} 秒`,
    durationCustom: "自定义",
    durationCustomLabel: "自定义时长（秒）",
    durationCustomPlaceholder: "5–120",
    durationRange: "请输入 5–120 秒",
    durationHint: "时长越长，生成越慢、消耗额度越多",
    // 文案/画面解耦（电商带货）
    ecomScriptLabel: "AI 口播文案（仅配音）",
    scenePromptLabel: "画面提示词",
    scenePromptGenerate: "AI 生成画面",
    scenePromptPlaceholder: "描述想要的产品画面 / 场景 / 镜头，可点「AI 生成画面」自动生成，也可手动编辑",
    scenePromptHint: "画面与口播已解耦：此处只描述画面，不影响配音文案",
    // 图片生成 / 修改（mode 值仍为 photo，仅显示文案）
    modePhoto: "图片生成 / 修改",
    photoTitle: "图片生成 / 修改",
    photoSubtitle: "一句话生成图片，或上传参考图换背景 / 修图",
    photoPromptLabel: "提示词",
    photoPromptPlaceholder: "描述想要的图片，如：白色大理石台面上的香水瓶，柔光氛围，高级质感",
    photoPromptRequired: "请先输入提示词",
    photoRefLabel: "参考图（可选）",
    photoRefUpload: "上传参考图（JPG / PNG / WebP，≤10MB）",
    photoRefPreviewAlt: "参考图预览",
    photoRefHint: "上传参考图做换背景 / 修图；留空则纯文生图",
    photoSizeLabel: "尺寸",
    photoQualityLabel: "质量",
    photoQuality: { low: "低", medium: "中", high: "高" },
    photoQualityHint: "质量越高，图片越精细、消耗积分越多",
    photoResultAlt: "生成的图片",
    // 文案仿写 + 标题/话题生成（mode: copywriting）
    modeCopywriting: "文案仿写",
    copyTitle: "文案仿写",
    copySubtitle: "粘贴参考文案，AI 改写并生成标题、话题",
    copySourceLabel: "参考文案",
    copySourcePlaceholder: "粘贴你有权使用的参考文案，AI 将据此改写",
    copySourceRequired: "请先粘贴参考文案",
    copyModeLabel: "改写模式",
    copyModeSmart: "智能",
    copyModeCustom: "自定义",
    copyModeAuto: "自动多版",
    copyInstructionLabel: "自定义指令",
    copyInstructionPlaceholder: "如：更口语、更简短、换高端风格",
    copyInstructionRequired: "请填写自定义改写指令",
    copyCountLabel: "候选数量",
    copyPlatformLabel: "目标平台（可选）",
    copyPlatformAny: "不限",
    copyPlatformDouyin: "抖音",
    copyPlatformXiaohongshu: "小红书",
    copyCompliance: "请确保你有权使用与改写所参考的文案",
    copyGenerate: "生成文案",
    copyGenerating: "生成中…",
    copyResultLabel: "改写文案（可编辑）",
    copyCandidatesLabel: "候选文案（点击选用）",
    copyTitlesLabel: "标题候选（点击复制）",
    copyTopicsLabel: "话题候选（点击复制）",
    copyEmptyTitles: "本次未生成标题候选",
    copyEmptyTopics: "本次未生成话题候选",
    copyCopy: "复制",
    copyCopied: "已复制",
    copySave: "保存到历史",
    copySaving: "保存中…",
    copySaved: "已保存",
    copyUseInAvatar: "用此文案 · 数字人口播",
    copyUseInEcom: "用此文案 · 电商带货",
    // 字幕样式（口播生产力增强 ORAL-PROD-UI-0001）；不选 = 默认烧入（不回归 0001）
    subtitleStyleLabel: "字幕样式（可选）",
    subtitleStyleHint: "不选用默认烧入样式；选预设后可微调字号 / 颜色 / 位置",
    subtitleStyleNone: "跟随默认",
    subtitleFontSizeLabel: "字号",
    subtitleColorLabel: "颜色",
    subtitlePositionLabel: "位置",
    subtitlePositionTop: "顶部",
    subtitlePositionCenter: "居中",
    subtitlePositionBottom: "底部",
    subtitleFontSizeRange: "字号需在 16–96",
    subtitlePreviewSample: "字幕预览示例文本",
    // 电商图 / 白底图抠图 (ECOM-IMG-UI-0001)
    modeEcomImage: "电商图",
    ecomCutoutTitle: "白底图 / 抠图",
    ecomCutoutSubtitle: "上传商品图，抠出商品换白底或透明底；支持批量",
    ecomModeSingle: "单张",
    ecomModeBatch: "批量",
    ecomBgLabel: "背景",
    ecomBgWhite: "白底",
    ecomBgTransparent: "透明底",
    ecomUploadLabel: "商品图",
    ecomUploadBatchLabel: "商品图（可多选，最多 20 张）",
    ecomUploadRequired: "请先上传商品图",
    ecomGenerate: "生成",
    ecomGenerating: "生成中…",
    ecomResultsLabel: "结果",
    ecomDownload: "下载",
    ecomDownloadAll: "批量下载",
    ecomBatchOverLimit: "批量最多 20 张，超出部分未添加",
    removeImage: "移除图片",
    // 电商图 · AI 模特 (ECOM-MODEL-UI-0001) — 子工具切换 + 模特偏好
    ecomSubToolLabel: "电商图工具",
    ecomSubToolCutout: "白底图",
    ecomSubToolModel: "AI 模特",
    ecomSubToolPoster: "营销海报",
    ecomModeGroupLabel: "生成方式",
    ecomModelTitle: "AI 模特",
    ecomModelSubtitle: "上传商品图，AI 生成上身模特展示图；支持批量",
    ecomGenderLabel: "模特性别",
    ecomGenderFemale: "女",
    ecomGenderMale: "男",
    ecomGenderAny: "不限",
    ecomStyleLabel: "风格预设",
    ecomStyleLoading: "加载风格预设…",
    ecomStyleError: "风格预设加载失败，请重试",
    ecomCustomLabel: "自定义补充（可选）",
    ecomCustomPlaceholder: "补充场景 / 姿态 / 氛围，如：暖光、街头、微笑站姿（≤200 字）",
    ecomModelCompliance: "模特图为 AI 生成，商品以实物为准",
    // 电商图 · 营销海报 (ECOM-POSTER-UI-0001)
    ecomPosterTitle: "营销海报",
    ecomPosterSubtitle: "上传商品图，套版式 + 标题文案，一键生成营销海报；支持批量",
    ecomTemplateLabel: "版式预设",
    ecomTemplateLoading: "加载版式预设…",
    ecomTemplateError: "版式预设加载失败，请重试",
    ecomPosterTitleLabel: "标题（可选）",
    ecomPosterTitlePlaceholder: "海报主标题，如：年中大促 全场 5 折",
    ecomPosterTaglineLabel: "自定义一行（可选）",
    ecomPosterTaglinePlaceholder: "副标题 / 卖点一行，如：限时 3 天 错过再等一年"
  },
  confirm: {
    title: "确定生成",
    estimating: "估算中…",
    estimatePrefix: "预计消耗 ",
    estimateSuffix: " 积分",
    estimateNote: "按实际生成时长结算",
    estimateUnavailable: "暂无法预估，按实际结算",
    warning: "确定生成即会消耗积分，生成过程中无法取消！",
    confirm: "确定",
    confirming: "提交中…",
    cancel: "取消"
  },
  errors: {
    quota: "额度不足，无法生成，请充值或精简任务",
    uploadTooLarge: "图片过大，请控制在 10MB 以内",
    uploadType: "仅支持 JPG / PNG / WebP 图片",
    network: "网络连接失败，请检查后端服务是否在线",
    generic: "操作失败，请重试",
    // 图片生成错误（按后端 error_code 映射；见 friendlyImageError）
    imageModeration: "内容被 AI 安全系统拦截，请调整描述后重试（避免敏感或人体性暗示内容）",
    imageConnection: "网络连接失败，请检查代理 / 网络后重试",
    imageInvalid: "生成参数有误，请调整尺寸 / 质量或描述后重试",
    imageGeneric: "图片生成失败，请重试",
    // 抠图透明底专属（IMAGE_ALPHA_MISSING）：可操作文案，不落通用兜底
    imageAlphaMissing: "透明底生成失败：未返回透明像素，请重试或改用白底",
    // 品牌音色音频上传/录音 (BRAND-VOICE-UI-0001)
    audioType: "仅支持 WAV / MP3 / M4A 音频",
    audioTooLarge: "音频过大，请控制在 20MB 以内",
    audioTooShort: "音频时长需至少 5 秒，请重录或换更长的音频"
  },
  tasks: {
    title: "生成任务",
    empty: "暂无任务，输入主题开始生成。",
    retry: "重试",
    retryUnavailable: "请到工作台重新发起",
    open: "查看详情",
    moreInHistory: "更多任务见下方「历史生成」"
  },
  history: {
    title: "历史生成",
    tabAvatar: "数字人视频历史",
    tabEcom: "电商视频历史",
    tabPhoto: "图片历史",
    tabCopy: "文案历史",
    empty: "暂无历史记录",
    loading: "加载中…",
    error: "加载失败，请重试",
    retry: "重试",
    loadMore: "加载更多",
    filterAllImages: "全部图片",
    filterCovers: "仅封面",
    deleteItem: "删除",
    clearAll: "清空",
    deleteConfirmTitle: "删除这条记录？",
    deleteConfirmHard: "将永久删除，不可恢复。",
    deleteConfirmSoft: "将从历史移除（可恢复）。",
    deleteConfirmBtn: "确认删除",
    clearConfirmTitle: "清空该历史？",
    clearConfirmHard: "将永久删除此模块全部记录，不可恢复。",
    clearConfirmPhotoHard: "将清空全部图片（含封面），硬删不可恢复；不受当前「仅封面」筛选影响（始终删除全部图片）。",
    clearConfirmSoft: "将清空此模块全部草稿（可恢复）。",
    clearConfirmBtn: "确认清空",
    deleteFailed: "删除失败，请重试",
    clearFailed: "清空失败，请重试"
  },
  detail: { notFound: "视频不存在或无权访问", back: "返回", download: "下载 MP4", downloadImage: "下载图片" },
  status: { queued: "排队中", failed: "失败", done: "已完成" },
  // 封面制作（口播视频产物附属 ORAL-PROD-UI-0001）
  cover: {
    entry: "做封面",
    title: "制作封面",
    subtitle: "从口播视频抽帧叠标题，或用 AI 生成封面",
    tabFrame: "截帧",
    tabAi: "AI 封面",
    frameLoading: "加载候选帧…",
    frameError: "候选帧加载失败，请重试",
    frameEmpty: "暂无候选帧",
    frameLabel: "选择封面帧",
    titleLabel: "封面标题（可选）",
    titlePlaceholder: "输入封面标题文字，可留空＝纯截帧",
    titleFontSizeLabel: "标题字号",
    titleColorLabel: "标题颜色",
    titlePositionLabel: "标题位置",
    titleFontSizeRange: "字号需在 24–120",
    generateFrame: "生成封面",
    generatingFrame: "生成中…",
    aiPromptLabel: "封面描述",
    aiPromptPlaceholder: "描述想要的封面画面，如：暖光下的咖啡杯特写，高级质感",
    generateAi: "AI 生成封面",
    generatingAi: "生成中…",
    aiPending: "封面生成中，完成后自动展示并存入图片历史…",
    aiDoneNoUrl: "已生成，请到图片历史查看",
    resultAlt: "封面预览",
    download: "下载封面",
    frameSaved: "封面已生成，可下载",
    savedToHistory: "已存入图片历史",
    retry: "重试"
  },
  // 品牌音色 / 声音克隆 (BRAND-VOICE-UI-0001)
  brandVoice: {
    entry: "我的品牌音色",
    pageTitle: "品牌音色",
    pageSubtitle: "录制或上传一段音频，克隆成你的专属口播音色",
    // 创建
    createTitle: "新建品牌音色",
    createSubtitle: "录一段或上传音频 → 试听 → 授权 → 创建",
    recordPrompt: "请用自然的语速朗读：「大家好，欢迎来到我的直播间，今天给大家带来一款超值好物。」",
    recordHint: "在安静环境录制，时长至少 5 秒，吐字清晰效果更好",
    recordStart: "开始录音",
    recordStop: "停止录音",
    recording: "录音中…",
    recordAgain: "重新录制",
    recordPermissionDenied: "麦克风权限被拒绝，请在浏览器允许后重试，或改用上传",
    recordUnsupported: "当前浏览器不支持录音，请改用上传音频",
    orUpload: "或上传音频",
    uploadAudio: "上传音频（WAV / MP3 / M4A，≤20MB）",
    audioReady: "音频已就绪，可试听",
    previewAria: "试听待克隆音频",
    removeAudio: "移除音频",
    nameLabel: "音色名称",
    namePlaceholder: "给你的品牌音色起个名字，如：我的主播音",
    consentLabel: "我已获得被克隆人的授权，并知悉生成内容为 AI 深度合成，将合法合规使用",
    consentRequired: "请先勾选授权声明后再创建",
    complianceHint: "未经授权克隆他人声音可能违法；请确保已获授权，生成内容为 AI 深度合成",
    create: "创建品牌音色",
    creating: "创建中…",
    createNeedAudio: "请先录制或上传一段音频",
    createNeedName: "请填写音色名称",
    // 列表
    listTitle: "我的品牌音色",
    listLoading: "加载中…",
    listError: "加载失败，请重试",
    listEmpty: "还没有品牌音色，录制或上传一段音频来创建",
    statusProcessing: "处理中",
    statusReady: "可用",
    statusFailed: "失败",
    processingHint: "声音克隆处理中，完成后即可在口播选用",
    delete: "删除",
    deleteConfirmTitle: "删除该品牌音色？",
    deleteConfirmMessage: "将永久删除，不可恢复；已生成的视频不受影响。",
    deleteConfirmBtn: "确认删除",
    // 口播 picker 分组
    pickerBrandGroup: "我的品牌音色",
    pickerStandardGroup: "系统音色"
  },
  // 深度合成标识设置 (LABEL-UI-0001)
  label: {
    entry: "标识设置",
    pageTitle: "深度合成标识",
    pageSubtitle: "设置 AI 生成内容的显式水印标识（位置 / 文案）",
    settingsTitle: "标识水印",
    positionLabel: "标识位置",
    posBr: "右下",
    posBl: "左下",
    posTr: "右上",
    posTl: "左上",
    posBc: "底部居中",
    textLabel: "标识文案",
    textPlaceholder: "如：AI 生成（≤20 字，必填）",
    textRequired: "标识文案不能为空",
    previewLabel: "实时预览",
    // 合规：不可关闭明示
    lockedTitle: "显式标识已开启，不可关闭",
    lockedHint: "根据深度合成合规要求，AI 生成内容必须带显式标识，无法关闭。",
    save: "保存",
    saving: "保存中…",
    saved: "已保存",
    // 产物处知情提示
    productNotice: "已含 AI 生成标识"
  }
} as const;
